@startuml

title Class Diagram - LO21 Project



class Jeu{

}
Jeu : +Jeu(extension : Extension)

class Carte {
 -id : string
 -nom : string
 -effet : string
 -coût : int
}
Carte : +getNom()
Carte : +getEffet()
Carte : +getCoût()

class Monument {
 -construit : bool
 
}
Monument : +estConstruit():bool
Monument : +construire()

class  Etablissement{

}


class  Partie{
 manche : int
 joueur_actif:*Joueur
 num_dé :int
 jeu : *Jeu
 joueurs : *Joueur
 réserve : *Réserve
 extension : Extension
 nb_joueurs : int
 nb_monuments :int
 nb_etablissements
}
Partie : +tour_joueur(joueur : Joueur)
Partie : +regarder_etablissements (joueur : Joueur, couleur : Couleur)
Parite : +application_regle_standard (couleur : Couleur)
Partie : +application_regle_speciale (pile_joueur : Pile)
Partie : +transaction_pièce(émetteur : Joueur, destinataire : Joueur, montant : int)
Partie : +transaction_carte(émetteur : Joueur, destinataire : Joueur, pile : Pile)
Partie : +achat_carte (joueur : Joueur, pile_réserve : Pile)
Partie : distribuer()


class  Réserve{
}
Réserve : Réserve (extension : Extension)
Réserve : retirer_carte(Pile pile)

class  Main{
-*Monument monuments[nb_monuments]
-*Etablissement etablissements[]
}


class Pile{
effectif : int
 num_dé : int
 type : Type
 nb_pièces: int
}
Pile : +getnb_type(couleur:Couleur,type : Type):int
Pile : +ajouter_etablissement(etablissement : *Etablissement)
Pile : +retirer_etablissement(etablissement : *Etablissement)
Pile : +estActif(num_dé : int):bool
Pile : +estSpecial()

class  Joueur{
 -id : int
 -pseudo : string
 -dés : 1..2
 -dés_lancés : 1..2
 -main : Main
 -compte : int
}

Joueur : +getNbDés()
Joueur : +setNbDés()
Joueur : +getCompte()
Joueur : +payer(montant:int)
Joueur : +encaisser(montant:int)
Joueur : +victoire():bool
Joueur : +lancerDés() : int


class Vert {
type_effet : Type
}
class Violet {
payeur : {all=0,one=1}
}
Jeu "1" *-- "*" Carte 
Carte <|-- Etablissement
Carte <|-- Monument
Partie "1" -- "1..4" Joueur
Joueur "1" -- "1" Main
Jeu "1" --o "1" Partie
Réserve "1" --o "1" Partie
Etablissement <|-- Rouge 
Etablissement <|-- Bleu
Etablissement <|-- Vert
Etablissement <|-- Violet
Pile "*" o-- "*" Etablissement
Réserve "1" o-- "*" Pile
Main "1" o-- "*" Monument
Main "1" o-- "*" Pile

' Creer un lien avec jeu et reserve entre la partie
hide @unlinked
@enduml

